/* AGSF Entrance Assessment — Question Bank
   Simple English, Maths, and General Knowledge questions.
   Each user receives 30 randomly selected & shuffled questions. */

const QUESTION_BANK = [
  // ===================== ENGLISH (50) =====================
  { subject: "English", q: "Choose the correct spelling.", options: ["Recieve", "Receive", "Receeve", "Receve"], answer: 1 },
  { subject: "English", q: "What is the plural of 'child'?", options: ["Childs", "Childes", "Children", "Childrens"], answer: 2 },
  { subject: "English", q: "Choose the synonym of 'Happy'.", options: ["Sad", "Joyful", "Angry", "Tired"], answer: 1 },
  { subject: "English", q: "Choose the antonym of 'Big'.", options: ["Large", "Huge", "Small", "Tall"], answer: 2 },
  { subject: "English", q: "Fill in the blank: She ___ to school every day.", options: ["go", "goes", "going", "gone"], answer: 1 },
  { subject: "English", q: "Which word is a noun?", options: ["Run", "Quickly", "Table", "Beautiful"], answer: 2 },
  { subject: "English", q: "Which word is a verb?", options: ["Jump", "Happy", "Blue", "Chair"], answer: 0 },
  { subject: "English", q: "Choose the correct sentence.", options: ["He don't like rice.", "He doesn't likes rice.", "He doesn't like rice.", "He not like rice."], answer: 2 },
  { subject: "English", q: "What is the opposite of 'Hot'?", options: ["Warm", "Cold", "Sunny", "Wet"], answer: 1 },
  { subject: "English", q: "Choose the correct plural of 'mouse'.", options: ["Mouses", "Mice", "Mouses", "Mices"], answer: 1 },
  { subject: "English", q: "Which sentence uses correct punctuation?", options: ["What is your name", "What is your name?", "what is your name?", "What is your name!"], answer: 1 },
  { subject: "English", q: "Choose the correct word: I have ___ apple.", options: ["a", "an", "the", "no article"], answer: 1 },
  { subject: "English", q: "Which word means the same as 'Begin'?", options: ["End", "Start", "Stop", "Finish"], answer: 1 },
  { subject: "English", q: "Choose the correct past tense of 'go'.", options: ["Goed", "Gone", "Went", "Going"], answer: 2 },
  { subject: "English", q: "Which is a question word?", options: ["What", "And", "But", "Because"], answer: 0 },
  { subject: "English", q: "Choose the correctly capitalized sentence.", options: ["my name is John.", "My name is john.", "My Name Is John.", "My name is John."], answer: 3 },
  { subject: "English", q: "What is the opposite of 'Up'?", options: ["High", "Down", "Top", "Above"], answer: 1 },
  { subject: "English", q: "Choose the correct word: They ___ playing football.", options: ["is", "am", "are", "be"], answer: 2 },
  { subject: "English", q: "Which word rhymes with 'Cat'?", options: ["Dog", "Hat", "Cup", "Pen"], answer: 1 },
  { subject: "English", q: "Choose the correct spelling.", options: ["Beautifull", "Beautiful", "Beutiful", "Beautyful"], answer: 1 },
  { subject: "English", q: "What type of word is 'quickly'?", options: ["Noun", "Verb", "Adjective", "Adverb"], answer: 3 },
  { subject: "English", q: "Choose the correct sentence.", options: ["She is my sister.", "She am my sister.", "She are my sister.", "She be my sister."], answer: 0 },
  { subject: "English", q: "What is the opposite of 'Open'?", options: ["Close", "Wide", "Free", "Loud"], answer: 0 },
  { subject: "English", q: "Choose the word that completes: The sun ___ in the east.", options: ["rise", "rises", "rising", "rose"], answer: 1 },
  { subject: "English", q: "Which is a color word?", options: ["Run", "Blue", "Fast", "Eat"], answer: 1 },
  { subject: "English", q: "Choose the correct plural of 'book'.", options: ["Bookes", "Book", "Books", "Bookies"], answer: 2 },
  { subject: "English", q: "What is the opposite of 'Day'?", options: ["Light", "Night", "Sun", "Morning"], answer: 1 },
  { subject: "English", q: "Choose the correct sentence.", options: ["I am happy.", "I is happy.", "I are happy.", "I be happy."], answer: 0 },
  { subject: "English", q: "Which word means 'very big'?", options: ["Tiny", "Huge", "Small", "Short"], answer: 1 },
  { subject: "English", q: "Choose the correct word: He ___ a doctor.", options: ["is", "am", "are", "be"], answer: 0 },
  { subject: "English", q: "What is the opposite of 'Fast'?", options: ["Quick", "Slow", "Strong", "Loud"], answer: 1 },
  { subject: "English", q: "Choose the correct spelling.", options: ["Friend", "Freind", "Frend", "Friand"], answer: 0 },
  { subject: "English", q: "Which sentence is in past tense?", options: ["I eat rice.", "I am eating rice.", "I ate rice.", "I will eat rice."], answer: 2 },
  { subject: "English", q: "What is the opposite of 'Happy'?", options: ["Glad", "Joyful", "Sad", "Excited"], answer: 2 },
  { subject: "English", q: "Choose the correct word: This is ___ book.", options: ["I", "my", "me", "mine is"], answer: 1 },
  { subject: "English", q: "Which is the correct greeting?", options: ["Good morning", "Goodmorning time", "Good-morning today", "Morning good"], answer: 0 },
  { subject: "English", q: "What is the plural of 'man'?", options: ["Mans", "Men", "Men's", "Mens"], answer: 1 },
  { subject: "English", q: "Choose the correct word: We ___ to the market yesterday.", options: ["go", "goes", "went", "going"], answer: 2 },
  { subject: "English", q: "Which word is an adjective?", options: ["Run", "Beautiful", "Quickly", "Jump"], answer: 1 },
  { subject: "English", q: "What is the opposite of 'Old'?", options: ["Young", "New", "Ancient", "Aged"], answer: 0 },
  { subject: "English", q: "Choose the correct sentence.", options: ["They has a car.", "They have a car.", "They having a car.", "They haves a car."], answer: 1 },
  { subject: "English", q: "Which word means 'a place to learn'?", options: ["Hospital", "Market", "School", "Farm"], answer: 2 },
  { subject: "English", q: "What is the opposite of 'Strong'?", options: ["Powerful", "Weak", "Tough", "Mighty"], answer: 1 },
  { subject: "English", q: "Choose the correct spelling.", options: ["Wensday", "Wednesday", "Wendsday", "Wednsday"], answer: 1 },
  { subject: "English", q: "Which is a fruit?", options: ["Carrot", "Mango", "Potato", "Onion"], answer: 1 },
  { subject: "English", q: "Choose the correct word: She is taller ___ me.", options: ["from", "than", "then", "as"], answer: 1 },
  { subject: "English", q: "What is the opposite of 'Easy'?", options: ["Simple", "Hard", "Light", "Quick"], answer: 1 },
  { subject: "English", q: "Choose the correct sentence.", options: ["He can to swim.", "He can swim.", "He can swims.", "He cans swim."], answer: 1 },
  { subject: "English", q: "Which word means 'to look for'?", options: ["Find", "Search", "Lose", "Keep"], answer: 1 },
  { subject: "English", q: "What is the opposite of 'Full'?", options: ["Empty", "Heavy", "Light", "Round"], answer: 0 },

  // ===================== MATHEMATICS (50) =====================
  { subject: "Mathematics", q: "What is 5 + 7?", options: ["10", "11", "12", "13"], answer: 2 },
  { subject: "Mathematics", q: "What is 9 - 4?", options: ["3", "4", "5", "6"], answer: 2 },
  { subject: "Mathematics", q: "What is 6 × 3?", options: ["16", "17", "18", "19"], answer: 2 },
  { subject: "Mathematics", q: "What is 20 ÷ 4?", options: ["4", "5", "6", "7"], answer: 1 },
  { subject: "Mathematics", q: "What is 12 + 8?", options: ["18", "19", "20", "21"], answer: 2 },
  { subject: "Mathematics", q: "What is 15 - 9?", options: ["4", "5", "6", "7"], answer: 2 },
  { subject: "Mathematics", q: "What is 7 × 2?", options: ["12", "13", "14", "15"], answer: 2 },
  { subject: "Mathematics", q: "What is 18 ÷ 3?", options: ["5", "6", "7", "8"], answer: 1 },
  { subject: "Mathematics", q: "What is half of 10?", options: ["3", "4", "5", "6"], answer: 2 },
  { subject: "Mathematics", q: "What is double of 6?", options: ["10", "11", "12", "13"], answer: 2 },
  { subject: "Mathematics", q: "How many sides does a triangle have?", options: ["2", "3", "4", "5"], answer: 1 },
  { subject: "Mathematics", q: "How many sides does a square have?", options: ["3", "4", "5", "6"], answer: 1 },
  { subject: "Mathematics", q: "What is 100 - 50?", options: ["40", "50", "60", "70"], answer: 1 },
  { subject: "Mathematics", q: "What is 3 + 3 + 3?", options: ["6", "7", "8", "9"], answer: 3 },
  { subject: "Mathematics", q: "What is 10 × 10?", options: ["10", "100", "1000", "20"], answer: 1 },
  { subject: "Mathematics", q: "What number comes after 19?", options: ["18", "20", "21", "22"], answer: 1 },
  { subject: "Mathematics", q: "What number comes before 30?", options: ["28", "29", "31", "32"], answer: 1 },
  { subject: "Mathematics", q: "What is 4 × 4?", options: ["12", "14", "16", "18"], answer: 2 },
  { subject: "Mathematics", q: "What is 25 + 25?", options: ["40", "45", "50", "55"], answer: 2 },
  { subject: "Mathematics", q: "What is 1/2 + 1/2?", options: ["1", "2", "1/4", "3/2"], answer: 0 },
  { subject: "Mathematics", q: "Which number is an even number?", options: ["3", "5", "8", "9"], answer: 2 },
  { subject: "Mathematics", q: "Which number is an odd number?", options: ["2", "4", "6", "7"], answer: 3 },
  { subject: "Mathematics", q: "What is 9 × 0?", options: ["0", "9", "1", "90"], answer: 0 },
  { subject: "Mathematics", q: "What is 8 + 8?", options: ["14", "15", "16", "17"], answer: 2 },
  { subject: "Mathematics", q: "How many days are in a week?", options: ["5", "6", "7", "8"], answer: 2 },
  { subject: "Mathematics", q: "How many months are in a year?", options: ["10", "11", "12", "13"], answer: 2 },
  { subject: "Mathematics", q: "What is 50 ÷ 5?", options: ["8", "9", "10", "11"], answer: 2 },
  { subject: "Mathematics", q: "What is 6 + 6 + 6?", options: ["16", "17", "18", "19"], answer: 2 },
  { subject: "Mathematics", q: "Which is the smallest number?", options: ["12", "8", "15", "20"], answer: 1 },
  { subject: "Mathematics", q: "Which is the largest number?", options: ["45", "54", "44", "40"], answer: 1 },
  { subject: "Mathematics", q: "What is 100 ÷ 10?", options: ["1", "10", "100", "1000"], answer: 1 },
  { subject: "Mathematics", q: "What is 13 + 7?", options: ["18", "19", "20", "21"], answer: 2 },
  { subject: "Mathematics", q: "What is 30 - 15?", options: ["10", "15", "20", "25"], answer: 1 },
  { subject: "Mathematics", q: "How many minutes are in an hour?", options: ["30", "45", "60", "100"], answer: 2 },
  { subject: "Mathematics", q: "How many hours are in a day?", options: ["12", "20", "24", "30"], answer: 2 },
  { subject: "Mathematics", q: "What is 2 × 9?", options: ["16", "17", "18", "19"], answer: 2 },
  { subject: "Mathematics", q: "What is 21 ÷ 3?", options: ["6", "7", "8", "9"], answer: 1 },
  { subject: "Mathematics", q: "What is 5 × 5?", options: ["20", "25", "30", "35"], answer: 1 },
  { subject: "Mathematics", q: "What shape has 4 equal sides and 4 right angles?", options: ["Circle", "Triangle", "Square", "Oval"], answer: 2 },
  { subject: "Mathematics", q: "What is 0 + 7?", options: ["0", "7", "70", "17"], answer: 1 },
  { subject: "Mathematics", q: "What is 16 - 8?", options: ["6", "7", "8", "9"], answer: 2 },
  { subject: "Mathematics", q: "What is 11 + 11?", options: ["20", "21", "22", "23"], answer: 2 },
  { subject: "Mathematics", q: "What comes next: 2, 4, 6, 8, ___?", options: ["9", "10", "11", "12"], answer: 1 },
  { subject: "Mathematics", q: "What comes next: 5, 10, 15, ___?", options: ["18", "20", "22", "25"], answer: 1 },
  { subject: "Mathematics", q: "What is 3 × 7?", options: ["18", "19", "20", "21"], answer: 3 },
  { subject: "Mathematics", q: "What is 40 ÷ 8?", options: ["4", "5", "6", "7"], answer: 1 },
  { subject: "Mathematics", q: "How many sides does a rectangle have?", options: ["2", "3", "4", "6"], answer: 2 },
  { subject: "Mathematics", q: "What is 9 + 9?", options: ["16", "17", "18", "19"], answer: 2 },
  { subject: "Mathematics", q: "What is 60 - 30?", options: ["20", "25", "30", "35"], answer: 2 },
  { subject: "Mathematics", q: "What is the value of zero plus zero?", options: ["0", "1", "10", "100"], answer: 0 },

  // ===================== GENERAL KNOWLEDGE (50) =====================
  { subject: "General Knowledge", q: "What color do you get when you mix blue and yellow?", options: ["Purple", "Green", "Orange", "Pink"], answer: 1 },
  { subject: "General Knowledge", q: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], answer: 2 },
  { subject: "General Knowledge", q: "What is the largest planet in our solar system?", options: ["Earth", "Mars", "Jupiter", "Saturn"], answer: 2 },
  { subject: "General Knowledge", q: "Which animal is known as the King of the Jungle?", options: ["Tiger", "Lion", "Elephant", "Leopard"], answer: 1 },
  { subject: "General Knowledge", q: "What do plants need to make their own food?", options: ["Sunlight", "Moonlight", "Darkness", "Smoke"], answer: 0 },
  { subject: "General Knowledge", q: "What is the capital city of Nigeria?", options: ["Lagos", "Abuja", "Kano", "Ibadan"], answer: 1 },
  { subject: "General Knowledge", q: "How many legs does a spider have?", options: ["6", "8", "10", "12"], answer: 1 },
  { subject: "General Knowledge", q: "What gas do humans breathe in to survive?", options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"], answer: 1 },
  { subject: "General Knowledge", q: "Which of these is a primary color?", options: ["Green", "Purple", "Red", "Orange"], answer: 2 },
  { subject: "General Knowledge", q: "What is the freezing point of water in Celsius?", options: ["0°C", "10°C", "50°C", "100°C"], answer: 0 },
  { subject: "General Knowledge", q: "What is the boiling point of water in Celsius?", options: ["50°C", "75°C", "90°C", "100°C"], answer: 3 },
  { subject: "General Knowledge", q: "Which organ pumps blood around the body?", options: ["Brain", "Lungs", "Heart", "Liver"], answer: 2 },
  { subject: "General Knowledge", q: "What do bees produce?", options: ["Milk", "Honey", "Silk", "Wax only"], answer: 1 },
  { subject: "General Knowledge", q: "How many days are in a leap year?", options: ["364", "365", "366", "367"], answer: 2 },
  { subject: "General Knowledge", q: "What is the closest star to Earth?", options: ["The Moon", "The Sun", "Mars", "Venus"], answer: 1 },
  { subject: "General Knowledge", q: "Which sense organ do we use to see?", options: ["Ears", "Nose", "Eyes", "Tongue"], answer: 2 },
  { subject: "General Knowledge", q: "Which animal is known for its long neck?", options: ["Elephant", "Giraffe", "Zebra", "Hippo"], answer: 1 },
  { subject: "General Knowledge", q: "What is frozen water called?", options: ["Steam", "Vapor", "Ice", "Mist"], answer: 2 },
  { subject: "General Knowledge", q: "How many wheels does a standard bicycle have?", options: ["1", "2", "3", "4"], answer: 1 },
  { subject: "General Knowledge", q: "What do we call a baby dog?", options: ["Kitten", "Puppy", "Cub", "Calf"], answer: 1 },
  { subject: "General Knowledge", q: "What do we call a baby cat?", options: ["Puppy", "Cub", "Kitten", "Chick"], answer: 2 },
  { subject: "General Knowledge", q: "Which continent is Nigeria located in?", options: ["Asia", "Africa", "Europe", "South America"], answer: 1 },
  { subject: "General Knowledge", q: "What is the main language used for international communication globally?", options: ["French", "English", "German", "Swahili"], answer: 1 },
  { subject: "General Knowledge", q: "Which part of the body do you use to smell?", options: ["Ears", "Eyes", "Nose", "Skin"], answer: 2 },
  { subject: "General Knowledge", q: "How many colors are in a rainbow?", options: ["5", "6", "7", "8"], answer: 2 },
  { subject: "General Knowledge", q: "What do we call the star that lights up our solar system?", options: ["Moon", "Sun", "Earth", "Comet"], answer: 1 },
  { subject: "General Knowledge", q: "Which of these is a vegetable?", options: ["Apple", "Mango", "Carrot", "Banana"], answer: 2 },
  { subject: "General Knowledge", q: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
  { subject: "General Knowledge", q: "Which animal is known for changing its skin color?", options: ["Lizard", "Chameleon", "Frog", "Snake"], answer: 1 },
  { subject: "General Knowledge", q: "What do we use to write on a chalkboard?", options: ["Pen", "Pencil", "Chalk", "Marker"], answer: 2 },
  { subject: "General Knowledge", q: "How many seasons are commonly recognised in many countries?", options: ["2", "3", "4", "5"], answer: 2 },
  { subject: "General Knowledge", q: "Which part of a plant absorbs water from the soil?", options: ["Leaf", "Flower", "Root", "Stem"], answer: 2 },
  { subject: "General Knowledge", q: "What do we call a place where books are kept for reading?", options: ["Hospital", "Library", "Market", "Bank"], answer: 1 },
  { subject: "General Knowledge", q: "What is the shape of the Earth?", options: ["Flat", "Square", "Round (sphere)", "Triangle"], answer: 2 },
  { subject: "General Knowledge", q: "Which animal is known to be man's best friend?", options: ["Cat", "Dog", "Horse", "Goat"], answer: 1 },
  { subject: "General Knowledge", q: "What do we call frozen rain?", options: ["Hail", "Fog", "Dew", "Mist"], answer: 0 },
  { subject: "General Knowledge", q: "Which meal do people usually eat in the morning?", options: ["Lunch", "Dinner", "Breakfast", "Supper"], answer: 2 },
  { subject: "General Knowledge", q: "What instrument is used to measure temperature?", options: ["Ruler", "Thermometer", "Scale", "Clock"], answer: 1 },
  { subject: "General Knowledge", q: "Which of these is used to tell time?", options: ["Clock", "Calendar", "Map", "Ruler"], answer: 0 },
  { subject: "General Knowledge", q: "What is the name of the natural satellite that orbits Earth?", options: ["Sun", "Mars", "Moon", "Star"], answer: 2 },
  { subject: "General Knowledge", q: "Which of these animals can fly?", options: ["Dog", "Fish", "Bird", "Cat"], answer: 2 },
  { subject: "General Knowledge", q: "What do we call a person who teaches students?", options: ["Doctor", "Teacher", "Driver", "Farmer"], answer: 1 },
  { subject: "General Knowledge", q: "What is the chief source of energy for the Earth?", options: ["Wind", "Sun", "Water", "Fire"], answer: 1 },
  { subject: "General Knowledge", q: "Which of these is a mode of transportation?", options: ["Car", "Chair", "Table", "Spoon"], answer: 0 },
  { subject: "General Knowledge", q: "What do we call the place where fish live?", options: ["Forest", "Desert", "Water", "Mountain"], answer: 2 },
  { subject: "General Knowledge", q: "How many letters are in the English alphabet?", options: ["24", "25", "26", "27"], answer: 2 },
  { subject: "General Knowledge", q: "Which of these is a farm animal?", options: ["Lion", "Cow", "Tiger", "Elephant"], answer: 1 },
  { subject: "General Knowledge", q: "What do we call the study of stars and space?", options: ["Biology", "Geography", "Astronomy", "Chemistry"], answer: 2 },
  { subject: "General Knowledge", q: "What is the name of the document that allows international travel?", options: ["License", "Passport", "Certificate", "ID Card"], answer: 1 }
];
